spec:
  replicas: 1
  template:
    spec:
      volumes:
        - name: config
          configMap:
            name: ${project.artifactId}
            items:
            - key: application.properties
              path: application.properties
        - name: secret-keystores
          secret:
            defaultMode: 420
            secretName: spring-boot-cxf-jaxrs-keystores
      containers:
        -
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 180
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 10
          volumeMounts:
            - mountPath: /etc/secret-keystores
              name: secret-keystores
            - name: config
              mountPath: /deployments/config
          env:
            - name: KEY_STORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-boot-cxf-jaxrs-passwords
                  key: server.ssl.key-store-password
            - name: TRUST_STORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-boot-cxf-jaxrs-passwords
                  key: server.ssl.key-store-password